Create the "add targets" API call feature file
vmware/repository-service-tuf pull request #116
Opened 2022-11-07 19:06 UTC by MVrachev

This is the first step toward resolving the issue https://github.com/vmware/repository-service-tuf/issues/47.

The feature file follows the [Gherkin](https://cucumber.io/docs/gherkin/reference/) language.

2022-11-08 12:39 UTC, MVrachev commented
After a conversation with @kairo a few changes were made:
- the `Background` section was removed so that an additional negative scenario when the token has insufficient scope can be documented
- an Example was added to the `Adding the same target twice using RSTUF API` scenario
- an additional commit was implemented adding a check of the completion of the task within a minute and a check that later the target file can be fetched.

2022-11-09 09:42 UTC, kairoaraujo requested changes
I'm adding some suggestions
- Use the Outline for the positive scenario, I think it gives a detailed view of the user scenario payload (data)
- Format the `Examples:`as tables with spaces for easy reading.

2022-11-09 09:42 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +    Scenario: Adding a target with insufficient token scope using RSTUF API
This Scenario is duplicated (line 28)

2022-11-09 09:42 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +            | 630 | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | "file1.tar.gz" |
Use the format as a table for better reading.
```suggestion
        Examples:
             | length | hashes                                                                 | custom | path           |
             | 630    | "13ae5bb136fac2878aff31522b9efb785519f98413ae5bb136fac2878aff31522b9e" | None   | "file4.tar.gz" |
```

2022-11-09 09:42 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +    Scenario: Adding a target with invalid information using RSTUF API
```suggestion
    Scenario Outline: Adding a target with invalid information using RSTUF API
```

2022-11-09 09:42 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +            | 630 | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} |  |
Formatting as ASCII table for better reading.
```suggestion
             | length | hashes                                                             | custom           | path           |
             | "a"    | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | "file1.tar.gz" |
             | 630    | "a"                                                                | {"key": "value"} | "file1.tar.gz" |
             | 630    | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | "a"              | "file1.tar.gz" |
             | 630    | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | None           |
             |        | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | "file1.tar.gz" |
             | 630    | None                                                               | {"key": "value"} | "file1.tar.gz" |
             | 630    | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a"| {"key": "value"} |                |```

2022-11-09 14:56 UTC, MVrachev commented on tests/features/targets/add_targets.feature
> +
I am not sure I see the benefit of adding different targets.
Here we are not testing RSTUF API behavior, but python-tuf behavior.
In `python-tuf` there is comprehensive testing creating different TargetFile objects: https://github.com/theupdateframework/python-tuf/blob/7311808f11990d1c726b2ba2c319f50b688b5bd3/tests/test_metadata_serialization.py#L552

2022-11-09 15:05 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +
The benefit here is to show the feature design for the API call. We are not testing the python-tuf but the API behavior.
You're specifying that the feature supports:
- One file with a custom field (as dictionary)
- One file without a custom field
- One file with a delegated path

2022-11-09 15:17 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +
Adding more context

- Ceremony configuration:

https://github.com/vmware/repository-service-tuf-cli/blob/6890e9ace3d70a00bf9c63ffdd6ecf850d3ffeee/repository_service_tuf/cli/admin/ceremony.py#L374-L376

- Delegation paths in the server:

https://github.com/vmware/repository-service-tuf-api/blob/b453e9a89cf0782118716052c7725f61229c4952/tests/data_examples/config/settings.json#L19-L22

2022-11-09 18:51 UTC, MVrachev commented
Addressed @kairoaraujo feedback. Ready for a new set of reviews.

2022-11-10 08:18 UTC, kairoaraujo reviewed
LGTM, only a tiny formatting fix.

2022-11-10 08:18 UTC, kairoaraujo commented on tests/features/targets/add_targets.feature
> +            | 630 | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} |                |
```suggestion
            | length | hashes                                                             | custom           | path           |
             | "a"   | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | "file1.tar.gz" |
             | 630   | "a"                                                                | {"key": "value"} | "file1.tar.gz" |
             | 630   | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | "a"              | "file1.tar.gz" |
             | 630   | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | None           |
             |       | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} | "file1.tar.gz" |
             | 630   |                                                                    | {"key": "value"} | "file1.tar.gz" |
             | 630   | "716f6e863f744b9ac22c97ec7b76ea5f5908bc5b2f67c61510bfc4751384ea7a" | {"key": "value"} |                |
```

2022-11-10 12:28 UTC, MVrachev commented
Ready for approval @kairoaraujo.

2022-11-10 12:33 UTC, kairoaraujo approved these changes

2022-11-11 10:32 UTC, MVrachev commented
@rdimitrov do you want to have a look at this file before it's merged?

2022-11-11 10:37 UTC, rdimitrov reviewed
Why did we have to update the CLI submodule reference? Otherwise, the feature description looks good 👍

2022-11-11 11:22 UTC, MVrachev commented
I just noticed there were changes there and decided to update.
I don't know when we are supposed to update and are there any guidelines around that @rdimitrov, @kairoaraujo?

2022-11-11 11:31 UTC, rdimitrov commented
> I just noticed there were changes there and decided to update.
> I don't know when we are supposed to update and are there any guidelines around that @rdimitrov, @kairoaraujo?

Ah, I see, I thought that this depends on something else introduced in CLI so thus why we added it as part of the PR.

Anyway, there's an automated daily mechanism that updates the references and run several tests against them (the exact functional tests this will be part of). This is how we ensure that the components we reference in the umbrella repository would work with each other flawlessly.

2022-11-11 11:32 UTC, rdimitrov approved these changes
I'll approve the changes while noting that even though we update the CLI the functional tests pass, so it should be okay 👍

2022-11-11 12:10 UTC, merged