Add functional tests for add_targets + small improvements
vmware/repository-service-tuf pull request #169
Opened 2022-12-10 14:52 UTC by MVrachev

The main changes in this pr are:
- adding functional tests for add_targets.feature file
- changes to the add_targets.feature file
- adding get_target_info() pytest feature inside conftest for future testing
- some small fixes 

Closes #47 

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

2022-12-12 14:38 UTC, rdimitrov requested changes
The FT need to be updated though 👍

2022-12-12 16:37 UTC, MVrachev commented
I have updated the `ngclient` fixture to use the content of the `metadata` directory generated by the CLI test https://github.com/vmware/repository-service-tuf-cli/blob/068c446e67cbed2ecf4250defb7bee6954994ed9/tests/unit/cli/admin/test_ceremony.py#L295
This was possible because of the lastest pr https://github.com/vmware/repository-service-tuf-cli/pull/148.

2022-12-13 13:06 UTC, MVrachev commented on tests/functional/targets/test_add_targets.py
> +    "the API requester has a token with a scope write for targets "
Yes, but this is for an older commit.
Given that we will squash all of them I don't think we need to fix that.

2022-12-14 13:45 UTC, kairoaraujo approved these changes
LGTM

2022-12-15 13:50 UTC, rdimitrov approved these changes

2022-12-15 14:13 UTC, merged