Update readthedocs url to a working one
vmware/repository-service-tuf pull request #243
Opened 2023-02-15 14:06 UTC by MVrachev

2023-02-15 14:18 UTC, kairoaraujo approved these changes

2023-02-15 19:55 UTC, KAUTH requested changes
Isn't the Development Guide URL this one, https://repository-service-tuf.readthedocs.io/en/latest/devel/index.html?

2023-02-16 07:41 UTC, kairoaraujo commented
> Isn't the Development Guide URL this one, https://repository-service-tuf.readthedocs.io/en/latest/devel/index.html?

Good point @KAUTH, I didn't notice it.

2023-02-16 07:43 UTC, kairoaraujo requested changes

2023-02-16 07:43 UTC, kairoaraujo commented on README.rst
> +<https://repository-service-tuf.readthedocs.io/>`_.
```suggestion
<https://repository-service-tuf.readthedocs.io/en/latest/devel/>`_.
```

2023-02-16 07:44 UTC, MVrachev commented
Okay, so the link I proposed is the official one and the one @KAUTH suggested is the development guide?
What's the difference between the two?

2023-02-16 20:40 UTC, KAUTH commented
> Okay, so the link I proposed is the official one and the one @KAUTH suggested is the development guide? What's the difference between the two?

AFAIU, I believe https://repository-service-tuf.readthedocs.io/ gives a general overview of RSTUF and its use-case (more for general users) and the other link is more focused on the development of RSTUF (more for contributors).

2023-02-20 19:25 UTC, kairoaraujo approved these changes

2023-02-21 10:43 UTC, MVrachev commented
I am working on a solution for the CI.
When we have it I will rebase the pr.

2023-02-21 20:05 UTC, KAUTH submitted a review, later dismissed

2023-02-22 05:57 UTC, MVrachev commented
I am sorry, but I had to rebase on top of the latest changes in the main branch which include a fix for the CI.
The approval status of your reviews has been dismissed by GitHub, so if you could give it again will be awesome.

2023-02-22 22:08 UTC, KAUTH commented
Sure thing @MVrachev!

2023-02-22 22:09 UTC, KAUTH approved these changes

2023-02-23 08:54 UTC, kairoaraujo approved these changes

2023-02-23 08:54 UTC, merged