Add load data information to the Guide
vmware/repository-service-tuf pull request #254
Opened 2023-02-24 15:02 UTC by kairoaraujo

Add a chapter with more details about using the load data feature from the CLI

2023-02-28 15:11 UTC, MVrachev requested changes

2023-02-28 15:11 UTC, MVrachev commented on docs/source/guide/deployment/importing-targets.rst
> +    using this feature only before going live with RSTUF.
I understand the idea of the warning, but the terminology sounds a little strange to me.
Do you mean they shouldn't replace the usage of RSTUF API to add their targets with "import-targets"?
If that's the case maybe we should also mention it a little more bluntly like:
``` suggestion
    Do not use "import targets" as a replacement for the standard procedure to
    add targets throughout the RSTUF API or CLI tool after RSTUF is deployed.
    This feature should only be used before going live with RSTUF.
```

2023-02-28 15:11 UTC, MVrachev commented on docs/source/guide/deployment/all_in_one.rst
> +5. Importing existent repository targets
``` suggestion
5. Importing existing repository targets
```

2023-02-28 15:11 UTC, MVrachev commented on docs/source/guide/deployment/all_in_one.rst
> +  If you want to import a huge existent data,
``` suggestion
  If you want to import a huge existing data,
```

2023-02-28 15:11 UTC, MVrachev commented on docs/source/guide/deployment/all_in_one.rst
> +  see :ref:`guide/deployment/importing-targets:Importing existent targets`
``` suggestion
  see :ref:`guide/deployment/importing-targets:Importing existing targets`
```

2023-02-28 15:11 UTC, MVrachev commented on docs/source/guide/deployment/importing-targets.rst
> +Importing existent targets
``` suggestion
Importing existing targets
```

2023-02-28 15:16 UTC, kairoaraujo commented on docs/source/guide/deployment/importing-targets.rst
> +RSTUF database updating the TUF Metadata.
I will modify it because there is no limit of a million targets.

2023-03-01 16:28 UTC, MVrachev requested changes
I saw one small change request, otherwise should be good to go.

2023-03-01 16:28 UTC, MVrachev commented on docs/source/guide/deployment/importing-targets.rst
> +will be slower than using the " import targets"  feature.
Something I missed in the first iteration:
```suggestion
If you decide, you can send all of the existing targets using the REST API, but it
will be slower than using the "import targets" feature.
```

2023-03-01 16:39 UTC, MVrachev approved these changes

2023-03-01 16:51 UTC, merged